### ISSUE TITLE
Allow commits directly to master

### ISSUE THREAD

**Issue by sarthak0415** [stilliard/github-task-list-completed#26] opened 2022-06-01 07:49 UTC
Hi ,

We have the following use cases - 
1. Devs can commit to 'master' branch via PR, where they are required to check all the checklist items on the PR.
2. Devs can use a separate review tool and commit directly to 'master' post the review.

UseCase#1 is handled via this app. But for UseCase#2 is there any way such that devs are allowed to commit directly to master. Github currently dosen't support that - https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-status-checks-before-merging

Maybe we can make a change such that the status pass for all incoming commits to the branch. Please let me know if this is possible

**Comment by stilliard** [comment] 2022-06-02 10:27
Hi @sarthak0415 

This sounds interesting, to check I understand:

Use case 1: Devs work on a new branch, open a PR and then the branch is merged to master. Like you said this works great for the check. 

Use case 2: Devs commit directly to master, I think in this case, our check wouldn't even get called correct? It should only run for a PR so if there's no PR involved then GitHub wont call our check sorry. 

You mentioned you use a separate review tool for use case 2, does this tool offer any sort of integration to add review comments as a new GitHub issue maybe as a work around? Our check still wont be called but you could at least track the tasks needed in that new issue?

For us we only follow the first use case, there's been a couple times when a commit or 2 was needed on master but to do this we manually allowed this for admins in the GitHub repo's settings, and then made a note for someone to review it later (as it was at about 3am but was urgently needed). So if your case is similar, opening a GitHub issue for those rarer times could work and introduces tracability into when and why this was done as the developer could explain why the commit was needed to be committed directly to master outside of the regular PR review process. 

What do you think? 
Let me know if I've misunderstood the 2nd use case btw. 

Thanks.

**Comment by sarthak0415** [comment] 2022-06-06 06:50
Hi @stilliard Thanks for the reply.

> Use case 2: Devs commit directly to master, I think in this case, our check wouldn't even get called correct? It should only run for a PR so if there's no PR involved then GitHub wont call our check sorry.
> You mentioned you use a separate review tool for use case 2, does this tool offer any sort of integration to add review comments as a new GitHub issue maybe as a work around? Our check still wont be called but you could at least track the tasks needed in that new issue?
> Let me know if I've misunderstood the 2nd use case btw.
Your understanding of 2nd use case is correct. 
We use a email based review for single line changes.

**We do not want the check to run for these commits, but devs should be able to commit them directly to master.**

> there's been a couple times when a commit or 2 was needed on master but to do this we manually allowed this for admins in the GitHub repo's settings, and then made a note for someone to review it later (as it was at about 3am but was urgently needed). So if your case is similar, opening a GitHub issue for those rarer times could work

We can't give admin access to devs, due to security reasons. Is there any other workaround ?

**Comment by stilliard** [comment] 2022-06-06 06:54
Hi @sarthak0415 
Just to check, are you saying the task list check is making the commits status not pass for them? It shouldn't be running for them at all as it should just be for PRs I believe. Commits directly to master shouldn't be touched by these checks.

**Comment by sarthak0415** [comment] 2022-06-06 07:52
Hi @stilliard ,

The status check fails when committing to master - 
```
> git push --force-with-lease
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 32 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 345 bytes | 345.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: This repository moved. Please use the new location:
remote:   https://github.com/org/repo.git
remote: 
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "task-list-completed" is expected.
To https://github.com/org/repo
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/org/
``` 

Btw this only happens for **non-Admins**.
Devs with admin permission are able to commit to master directly without raising a PR.

**Comment by stilliard** [comment] 2022-06-06 08:33
Hi @sarthak0415 

Interesting, I think I don't see this as i'm an admin on all my repo's atm. 

I think as you want to allow people to push to master, one fix is to set this check to not be required. 
Over in the branch protection settings I think you can remove the check from the required list. It should still be called during PR's but it wont then be required before merges. This should then let you push to master without it. 
Would that work for you?

**Comment by sarthak0415** [comment] 2022-06-06 10:50
> I think as you want to allow people to push to master, one fix is to set this check to not be required.
Over in the branch protection settings I think you can remove the check from the required list. It should still be called during PR's but it wont then be required before merges. This should then let you push to master without it.
Would that work for you?

Yes currently we are following **no-check** for this app. But we would want 
1. This check to be blocking for a PR.
2. This check to be non-existent while committing to master

**Comment by stilliard** [comment] 2022-06-06 18:33
Hi @sarthak0415 
I've had a nother look through the protected branches docs, I think the issue is from GitHub that you're protecting the master/main branch with this check, but then also saying they can bypass it only when not doing a PR. 
The check only gets run when a PR is opened/edited or a comment is added so we have no way atm to have the check run for every commit instead: https://github.com/stilliard/github-task-list-completed/blob/master/index.js#L9

One thing you could look into is if you fork the project, you could try changing the events the check listens to ref the above link and see if hosting it yourself you can get it to run for every commit regardless of a PR or not? 
Not sure if that's possible or not sorry but worth a check into.

**Closed as not planned** 2022-07-23 13:18 UTC
