### ISSUE TITLE
Check tasks in linked issues

### ISSUE THREAD

**Issue by frederikheld** [stilliard/github-task-list-completed#12] opened 2020-05-29 02:07 UTC
Thank you for this app!

For my workflow it would be great if it would check open tasks in linked issues as well.

Context: for new features I'm working with user stories and each acceptance criteria is a task. As all acceptance criteria have to be met before the work is done (aka the PR can be merged), it would make sense to have this checked automatically. GitHub already displays a little indicator about the number of tasks closed/total, but having it as a status check would be even better.

I also support #2 and #8 which would improve the review process.

**Comment by stilliard** [comment] 2020-06-17 08:02
Hey @frederikheld 
I think this could be an interesting opt-in feature. 
For my use case I sometimes have epics / larger issues with multiple pull requests but for most projects I use a single issue and pull request and this would fit that great. 

I think we'll have a look into this more after working on #2

**Comment by koobs** [comment] 2020-07-27 05:16
Our flow is single card with tasklists, with multiple PR's as people work through those tasks. PR's don't contain task items, but all PR's reference the related issue ID, that does contain the tasklist

**Comment by stilliard** [comment] 2020-07-27 10:51
@koobs Interesting, so would you want this to check the issue checklists are all complete or that a specific list on the issue is complete? the latter would be more tricky as it'd need some way to relate each list on the card to each issue.

**Comment by koobs** [comment] 2020-07-27 12:01
Yeh I think for starters just checking that all tasks of issues refenced in a PR is a good start.

The goal here is that PR authors get a check/reminder that the tasks are checked. The problems solved are:

 * Authors may forget certain tasks in their PR.
 * Requires authors to actually tick task items, closing the issue management loop

An idea for what could be done for checking *specific* tasks in PRs might be to use a special extended syntax for items like:

Issue #1

 - [ ] acceptance criteria foo (%1)
 - [ ] acceptance criteria bar (%2)

PR:

Add feature

This PR adds feature

References #1 (%1)

-----

Check output: 1 of 2 tasks complete, see #1

-----

If no "(%x)" was referenced:

-----

Check output: 0 of 2 tasks complete, see #1

**Comment by stilliard** [comment] 2023-10-25 16:51
Having a look through some older issues and spotted this one. 
I still like the idea but I think it'd do better as a separate github check. 

One thing I've seen lately over the last year is slowness with multiple api requests back to github during the check which this would increase. 

Instead if this was a fork of this project but with the api checks changed to look at the original issue instead of the pr body or comments, then you could run both and even have it use the comments of the original issue. 

Closing this for now but hope the above ideas help anyone who might be interested to work on a fork to do this. 
Thanks.

**Closed as completed by stilliard** 2023-10-25 16:51 UTC
Labels: enhancement
